// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Answers is the predicate function for answers builders.
type Answers func(*sql.Selector)

// Attempt is the predicate function for attempt builders.
type Attempt func(*sql.Selector)

// Attempt_answers is the predicate function for attempt_answers builders.
type Attempt_answers func(*sql.Selector)

// Questions is the predicate function for questions builders.
type Questions func(*sql.Selector)

// Quiz is the predicate function for quiz builders.
type Quiz func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
