-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" text NOT NULL,
  "password_hash" text NOT NULL,
  "role" character varying NOT NULL DEFAULT 'user',
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "quizs" table
CREATE TABLE "quizs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" text NOT NULL,
  "is_published" boolean NOT NULL DEFAULT false,
  "pass_threshold" bigint NULL,
  "one_attempt" boolean NOT NULL DEFAULT false,
  "show_answers" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "user_quizzes" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "quizs_users_quizzes" FOREIGN KEY ("user_quizzes") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "quiz_is_published" to table: "quizs"
CREATE INDEX "quiz_is_published" ON "quizs" ("is_published");
-- Create "questions" table
CREATE TABLE "questions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "text" text NOT NULL,
  "order_index" bigint NOT NULL,
  "quiz_questions" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "questions_quizs_questions" FOREIGN KEY ("quiz_questions") REFERENCES "quizs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "questions_order_index" to table: "questions"
CREATE INDEX "questions_order_index" ON "questions" ("order_index");
-- Create index "questions_order_index_quiz_questions" to table: "questions"
CREATE UNIQUE INDEX "questions_order_index_quiz_questions" ON "questions" ("order_index", "quiz_questions");
-- Create "answers" table
CREATE TABLE "answers" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "text" text NOT NULL,
  "is_correct" boolean NOT NULL DEFAULT false,
  "order_index" bigint NOT NULL,
  "questions_answers" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "answers_questions_answers" FOREIGN KEY ("questions_answers") REFERENCES "questions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "answers_order_index_questions_answers" to table: "answers"
CREATE UNIQUE INDEX "answers_order_index_questions_answers" ON "answers" ("order_index", "questions_answers");
-- Create "attempts" table
CREATE TABLE "attempts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "score" bigint NOT NULL,
  "total" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  "quiz_attempts" bigint NOT NULL,
  "user_attempts" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "attempts_quizs_attempts" FOREIGN KEY ("quiz_attempts") REFERENCES "quizs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "attempts_users_attempts" FOREIGN KEY ("user_attempts") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "attempt_created_at_user_attempts_quiz_attempts" to table: "attempts"
CREATE INDEX "attempt_created_at_user_attempts_quiz_attempts" ON "attempts" ("created_at", "user_attempts", "quiz_attempts");
-- Create "attempt_answers" table
CREATE TABLE "attempt_answers" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "attempt_attempt_answers" bigint NOT NULL,
  "attempt_answers_question" bigint NOT NULL,
  "attempt_answers_answer" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "attempt_answers_answers_answer" FOREIGN KEY ("attempt_answers_answer") REFERENCES "answers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "attempt_answers_attempts_attempt_answers" FOREIGN KEY ("attempt_attempt_answers") REFERENCES "attempts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "attempt_answers_questions_question" FOREIGN KEY ("attempt_answers_question") REFERENCES "questions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "attempt_answers_attempt_attempt_answers_attempt_answers_questio" to table: "attempt_answers"
CREATE UNIQUE INDEX "attempt_answers_attempt_attempt_answers_attempt_answers_questio" ON "attempt_answers" ("attempt_attempt_answers", "attempt_answers_question");
