// Code generated by encore. DO NOT EDIT.

package hello

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// This is a public REST API that responds with a personalized greeting.
	// Learn more about defining APIs with Encore:
	// https://encore.dev/docs/primitives/services-and-apis
	//
	// To call it, run in your terminal:
	//
	//	curl http://localhost:4000/hello/World
	World(ctx context.Context, name string) (*Response, error)
}
