// Code generated by ent, DO NOT EDIT.

package attempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the attempt type in the database.
	Label = "attempt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldTotal holds the string denoting the total field in the database.
	FieldTotal = "total"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeQuiz holds the string denoting the quiz edge name in mutations.
	EdgeQuiz = "quiz"
	// EdgeAttemptAnswers holds the string denoting the attempt_answers edge name in mutations.
	EdgeAttemptAnswers = "attempt_answers"
	// Table holds the table name of the attempt in the database.
	Table = "attempts"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "attempts"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_attempts"
	// QuizTable is the table that holds the quiz relation/edge.
	QuizTable = "attempts"
	// QuizInverseTable is the table name for the Quiz entity.
	// It exists in this package in order to avoid circular dependency with the "quiz" package.
	QuizInverseTable = "quizs"
	// QuizColumn is the table column denoting the quiz relation/edge.
	QuizColumn = "quiz_attempts"
	// AttemptAnswersTable is the table that holds the attempt_answers relation/edge.
	AttemptAnswersTable = "attempt_answers"
	// AttemptAnswersInverseTable is the table name for the Attempt_answers entity.
	// It exists in this package in order to avoid circular dependency with the "attempt_answers" package.
	AttemptAnswersInverseTable = "attempt_answers"
	// AttemptAnswersColumn is the table column denoting the attempt_answers relation/edge.
	AttemptAnswersColumn = "attempt_attempt_answers"
)

// Columns holds all SQL columns for attempt fields.
var Columns = []string{
	FieldID,
	FieldScore,
	FieldTotal,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "attempts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"quiz_attempts",
	"user_attempts",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ScoreValidator is a validator for the "score" field. It is called by the builders before save.
	ScoreValidator func(int) error
	// TotalValidator is a validator for the "total" field. It is called by the builders before save.
	TotalValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Attempt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByTotal orders the results by the total field.
func ByTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotal, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByQuizField orders the results by quiz field.
func ByQuizField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuizStep(), sql.OrderByField(field, opts...))
	}
}

// ByAttemptAnswersCount orders the results by attempt_answers count.
func ByAttemptAnswersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttemptAnswersStep(), opts...)
	}
}

// ByAttemptAnswers orders the results by attempt_answers terms.
func ByAttemptAnswers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttemptAnswersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newQuizStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuizInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, QuizTable, QuizColumn),
	)
}
func newAttemptAnswersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttemptAnswersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttemptAnswersTable, AttemptAnswersColumn),
	)
}
