// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/questions"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnswersCreate is the builder for creating a Answers entity.
type AnswersCreate struct {
	config
	mutation *AnswersMutation
	hooks    []Hook
}

// SetText sets the "text" field.
func (_c *AnswersCreate) SetText(v string) *AnswersCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetIsCorrect sets the "is_correct" field.
func (_c *AnswersCreate) SetIsCorrect(v bool) *AnswersCreate {
	_c.mutation.SetIsCorrect(v)
	return _c
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (_c *AnswersCreate) SetNillableIsCorrect(v *bool) *AnswersCreate {
	if v != nil {
		_c.SetIsCorrect(*v)
	}
	return _c
}

// SetOrderIndex sets the "order_index" field.
func (_c *AnswersCreate) SetOrderIndex(v int) *AnswersCreate {
	_c.mutation.SetOrderIndex(v)
	return _c
}

// SetQuestionID sets the "question" edge to the Questions entity by ID.
func (_c *AnswersCreate) SetQuestionID(id int) *AnswersCreate {
	_c.mutation.SetQuestionID(id)
	return _c
}

// SetQuestion sets the "question" edge to the Questions entity.
func (_c *AnswersCreate) SetQuestion(v *Questions) *AnswersCreate {
	return _c.SetQuestionID(v.ID)
}

// Mutation returns the AnswersMutation object of the builder.
func (_c *AnswersCreate) Mutation() *AnswersMutation {
	return _c.mutation
}

// Save creates the Answers in the database.
func (_c *AnswersCreate) Save(ctx context.Context) (*Answers, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnswersCreate) SaveX(ctx context.Context) *Answers {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnswersCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnswersCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnswersCreate) defaults() {
	if _, ok := _c.mutation.IsCorrect(); !ok {
		v := answers.DefaultIsCorrect
		_c.mutation.SetIsCorrect(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnswersCreate) check() error {
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Answers.text"`)}
	}
	if _, ok := _c.mutation.IsCorrect(); !ok {
		return &ValidationError{Name: "is_correct", err: errors.New(`ent: missing required field "Answers.is_correct"`)}
	}
	if _, ok := _c.mutation.OrderIndex(); !ok {
		return &ValidationError{Name: "order_index", err: errors.New(`ent: missing required field "Answers.order_index"`)}
	}
	if len(_c.mutation.QuestionIDs()) == 0 {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required edge "Answers.question"`)}
	}
	return nil
}

func (_c *AnswersCreate) sqlSave(ctx context.Context) (*Answers, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnswersCreate) createSpec() (*Answers, *sqlgraph.CreateSpec) {
	var (
		_node = &Answers{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(answers.Table, sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(answers.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.IsCorrect(); ok {
		_spec.SetField(answers.FieldIsCorrect, field.TypeBool, value)
		_node.IsCorrect = value
	}
	if value, ok := _c.mutation.OrderIndex(); ok {
		_spec.SetField(answers.FieldOrderIndex, field.TypeInt, value)
		_node.OrderIndex = value
	}
	if nodes := _c.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answers.QuestionTable,
			Columns: []string{answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.questions_answers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnswersCreateBulk is the builder for creating many Answers entities in bulk.
type AnswersCreateBulk struct {
	config
	err      error
	builders []*AnswersCreate
}

// Save creates the Answers entities in the database.
func (_c *AnswersCreateBulk) Save(ctx context.Context) ([]*Answers, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Answers, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnswersMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnswersCreateBulk) SaveX(ctx context.Context) []*Answers {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnswersCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnswersCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
