// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/questions"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Answers is the model entity for the Answers schema.
type Answers struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// IsCorrect holds the value of the "is_correct" field.
	IsCorrect bool `json:"is_correct,omitempty"`
	// OrderIndex holds the value of the "order_index" field.
	OrderIndex int `json:"order_index,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnswersQuery when eager-loading is set.
	Edges             AnswersEdges `json:"edges"`
	questions_answers *int
	selectValues      sql.SelectValues
}

// AnswersEdges holds the relations/edges for other nodes in the graph.
type AnswersEdges struct {
	// Question holds the value of the question edge.
	Question *Questions `json:"question,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnswersEdges) QuestionOrErr() (*Questions, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: questions.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Answers) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case answers.FieldIsCorrect:
			values[i] = new(sql.NullBool)
		case answers.FieldID, answers.FieldOrderIndex:
			values[i] = new(sql.NullInt64)
		case answers.FieldText:
			values[i] = new(sql.NullString)
		case answers.ForeignKeys[0]: // questions_answers
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Answers fields.
func (_m *Answers) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case answers.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case answers.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case answers.FieldIsCorrect:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_correct", values[i])
			} else if value.Valid {
				_m.IsCorrect = value.Bool
			}
		case answers.FieldOrderIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_index", values[i])
			} else if value.Valid {
				_m.OrderIndex = int(value.Int64)
			}
		case answers.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field questions_answers", value)
			} else if value.Valid {
				_m.questions_answers = new(int)
				*_m.questions_answers = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Answers.
// This includes values selected through modifiers, order, etc.
func (_m *Answers) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuestion queries the "question" edge of the Answers entity.
func (_m *Answers) QueryQuestion() *QuestionsQuery {
	return NewAnswersClient(_m.config).QueryQuestion(_m)
}

// Update returns a builder for updating this Answers.
// Note that you need to call Answers.Unwrap() before calling this method if this Answers
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Answers) Update() *AnswersUpdateOne {
	return NewAnswersClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Answers entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Answers) Unwrap() *Answers {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Answers is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Answers) String() string {
	var builder strings.Builder
	builder.WriteString("Answers(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("is_correct=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCorrect))
	builder.WriteString(", ")
	builder.WriteString("order_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderIndex))
	builder.WriteByte(')')
	return builder.String()
}

// AnswersSlice is a parsable slice of Answers.
type AnswersSlice []*Answers
