// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/predicate"
	"quizsystem/internal/store/ent/questions"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnswersUpdate is the builder for updating Answers entities.
type AnswersUpdate struct {
	config
	hooks    []Hook
	mutation *AnswersMutation
}

// Where appends a list predicates to the AnswersUpdate builder.
func (_u *AnswersUpdate) Where(ps ...predicate.Answers) *AnswersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *AnswersUpdate) SetText(v string) *AnswersUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *AnswersUpdate) SetNillableText(v *string) *AnswersUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetIsCorrect sets the "is_correct" field.
func (_u *AnswersUpdate) SetIsCorrect(v bool) *AnswersUpdate {
	_u.mutation.SetIsCorrect(v)
	return _u
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (_u *AnswersUpdate) SetNillableIsCorrect(v *bool) *AnswersUpdate {
	if v != nil {
		_u.SetIsCorrect(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *AnswersUpdate) SetOrderIndex(v int) *AnswersUpdate {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *AnswersUpdate) SetNillableOrderIndex(v *int) *AnswersUpdate {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *AnswersUpdate) AddOrderIndex(v int) *AnswersUpdate {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetQuestionID sets the "question" edge to the Questions entity by ID.
func (_u *AnswersUpdate) SetQuestionID(id int) *AnswersUpdate {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetQuestion sets the "question" edge to the Questions entity.
func (_u *AnswersUpdate) SetQuestion(v *Questions) *AnswersUpdate {
	return _u.SetQuestionID(v.ID)
}

// Mutation returns the AnswersMutation object of the builder.
func (_u *AnswersUpdate) Mutation() *AnswersMutation {
	return _u.mutation
}

// ClearQuestion clears the "question" edge to the Questions entity.
func (_u *AnswersUpdate) ClearQuestion() *AnswersUpdate {
	_u.mutation.ClearQuestion()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnswersUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnswersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnswersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnswersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnswersUpdate) check() error {
	if _u.mutation.QuestionCleared() && len(_u.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Answers.question"`)
	}
	return nil
}

func (_u *AnswersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(answers.Table, answers.Columns, sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(answers.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCorrect(); ok {
		_spec.SetField(answers.FieldIsCorrect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(answers.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(answers.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answers.QuestionTable,
			Columns: []string{answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answers.QuestionTable,
			Columns: []string{answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnswersUpdateOne is the builder for updating a single Answers entity.
type AnswersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnswersMutation
}

// SetText sets the "text" field.
func (_u *AnswersUpdateOne) SetText(v string) *AnswersUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *AnswersUpdateOne) SetNillableText(v *string) *AnswersUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetIsCorrect sets the "is_correct" field.
func (_u *AnswersUpdateOne) SetIsCorrect(v bool) *AnswersUpdateOne {
	_u.mutation.SetIsCorrect(v)
	return _u
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (_u *AnswersUpdateOne) SetNillableIsCorrect(v *bool) *AnswersUpdateOne {
	if v != nil {
		_u.SetIsCorrect(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *AnswersUpdateOne) SetOrderIndex(v int) *AnswersUpdateOne {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *AnswersUpdateOne) SetNillableOrderIndex(v *int) *AnswersUpdateOne {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *AnswersUpdateOne) AddOrderIndex(v int) *AnswersUpdateOne {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetQuestionID sets the "question" edge to the Questions entity by ID.
func (_u *AnswersUpdateOne) SetQuestionID(id int) *AnswersUpdateOne {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetQuestion sets the "question" edge to the Questions entity.
func (_u *AnswersUpdateOne) SetQuestion(v *Questions) *AnswersUpdateOne {
	return _u.SetQuestionID(v.ID)
}

// Mutation returns the AnswersMutation object of the builder.
func (_u *AnswersUpdateOne) Mutation() *AnswersMutation {
	return _u.mutation
}

// ClearQuestion clears the "question" edge to the Questions entity.
func (_u *AnswersUpdateOne) ClearQuestion() *AnswersUpdateOne {
	_u.mutation.ClearQuestion()
	return _u
}

// Where appends a list predicates to the AnswersUpdate builder.
func (_u *AnswersUpdateOne) Where(ps ...predicate.Answers) *AnswersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnswersUpdateOne) Select(field string, fields ...string) *AnswersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Answers entity.
func (_u *AnswersUpdateOne) Save(ctx context.Context) (*Answers, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnswersUpdateOne) SaveX(ctx context.Context) *Answers {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnswersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnswersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnswersUpdateOne) check() error {
	if _u.mutation.QuestionCleared() && len(_u.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Answers.question"`)
	}
	return nil
}

func (_u *AnswersUpdateOne) sqlSave(ctx context.Context) (_node *Answers, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(answers.Table, answers.Columns, sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Answers.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, answers.FieldID)
		for _, f := range fields {
			if !answers.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != answers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(answers.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCorrect(); ok {
		_spec.SetField(answers.FieldIsCorrect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(answers.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(answers.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answers.QuestionTable,
			Columns: []string{answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answers.QuestionTable,
			Columns: []string{answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Answers{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
