// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/attempt"
	"quizsystem/internal/store/ent/attempt_answers"
	"quizsystem/internal/store/ent/questions"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Attempt_answers is the model entity for the Attempt_answers schema.
type Attempt_answers struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the Attempt_answersQuery when eager-loading is set.
	Edges                    Attempt_answersEdges `json:"edges"`
	attempt_attempt_answers  *int
	attempt_answers_question *int
	attempt_answers_answer   *int
	selectValues             sql.SelectValues
}

// Attempt_answersEdges holds the relations/edges for other nodes in the graph.
type Attempt_answersEdges struct {
	// Attempt holds the value of the attempt edge.
	Attempt *Attempt `json:"attempt,omitempty"`
	// Question holds the value of the question edge.
	Question *Questions `json:"question,omitempty"`
	// Answer holds the value of the answer edge.
	Answer *Answers `json:"answer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AttemptOrErr returns the Attempt value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Attempt_answersEdges) AttemptOrErr() (*Attempt, error) {
	if e.Attempt != nil {
		return e.Attempt, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: attempt.Label}
	}
	return nil, &NotLoadedError{edge: "attempt"}
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Attempt_answersEdges) QuestionOrErr() (*Questions, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: questions.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// AnswerOrErr returns the Answer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Attempt_answersEdges) AnswerOrErr() (*Answers, error) {
	if e.Answer != nil {
		return e.Answer, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: answers.Label}
	}
	return nil, &NotLoadedError{edge: "answer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Attempt_answers) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attempt_answers.FieldID:
			values[i] = new(sql.NullInt64)
		case attempt_answers.ForeignKeys[0]: // attempt_attempt_answers
			values[i] = new(sql.NullInt64)
		case attempt_answers.ForeignKeys[1]: // attempt_answers_question
			values[i] = new(sql.NullInt64)
		case attempt_answers.ForeignKeys[2]: // attempt_answers_answer
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Attempt_answers fields.
func (_m *Attempt_answers) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attempt_answers.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case attempt_answers.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field attempt_attempt_answers", value)
			} else if value.Valid {
				_m.attempt_attempt_answers = new(int)
				*_m.attempt_attempt_answers = int(value.Int64)
			}
		case attempt_answers.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field attempt_answers_question", value)
			} else if value.Valid {
				_m.attempt_answers_question = new(int)
				*_m.attempt_answers_question = int(value.Int64)
			}
		case attempt_answers.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field attempt_answers_answer", value)
			} else if value.Valid {
				_m.attempt_answers_answer = new(int)
				*_m.attempt_answers_answer = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Attempt_answers.
// This includes values selected through modifiers, order, etc.
func (_m *Attempt_answers) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAttempt queries the "attempt" edge of the Attempt_answers entity.
func (_m *Attempt_answers) QueryAttempt() *AttemptQuery {
	return NewAttemptAnswersClient(_m.config).QueryAttempt(_m)
}

// QueryQuestion queries the "question" edge of the Attempt_answers entity.
func (_m *Attempt_answers) QueryQuestion() *QuestionsQuery {
	return NewAttemptAnswersClient(_m.config).QueryQuestion(_m)
}

// QueryAnswer queries the "answer" edge of the Attempt_answers entity.
func (_m *Attempt_answers) QueryAnswer() *AnswersQuery {
	return NewAttemptAnswersClient(_m.config).QueryAnswer(_m)
}

// Update returns a builder for updating this Attempt_answers.
// Note that you need to call Attempt_answers.Unwrap() before calling this method if this Attempt_answers
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Attempt_answers) Update() *AttemptAnswersUpdateOne {
	return NewAttemptAnswersClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Attempt_answers entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Attempt_answers) Unwrap() *Attempt_answers {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Attempt_answers is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Attempt_answers) String() string {
	var builder strings.Builder
	builder.WriteString("Attempt_answers(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Attempt_answersSlice is a parsable slice of Attempt_answers.
type Attempt_answersSlice []*Attempt_answers
