// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/attempt"
	"quizsystem/internal/store/ent/attempt_answers"
	"quizsystem/internal/store/ent/questions"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttemptAnswersCreate is the builder for creating a Attempt_answers entity.
type AttemptAnswersCreate struct {
	config
	mutation *AttemptAnswersMutation
	hooks    []Hook
}

// SetAttemptID sets the "attempt" edge to the Attempt entity by ID.
func (_c *AttemptAnswersCreate) SetAttemptID(id int) *AttemptAnswersCreate {
	_c.mutation.SetAttemptID(id)
	return _c
}

// SetAttempt sets the "attempt" edge to the Attempt entity.
func (_c *AttemptAnswersCreate) SetAttempt(v *Attempt) *AttemptAnswersCreate {
	return _c.SetAttemptID(v.ID)
}

// SetQuestionID sets the "question" edge to the Questions entity by ID.
func (_c *AttemptAnswersCreate) SetQuestionID(id int) *AttemptAnswersCreate {
	_c.mutation.SetQuestionID(id)
	return _c
}

// SetQuestion sets the "question" edge to the Questions entity.
func (_c *AttemptAnswersCreate) SetQuestion(v *Questions) *AttemptAnswersCreate {
	return _c.SetQuestionID(v.ID)
}

// SetAnswerID sets the "answer" edge to the Answers entity by ID.
func (_c *AttemptAnswersCreate) SetAnswerID(id int) *AttemptAnswersCreate {
	_c.mutation.SetAnswerID(id)
	return _c
}

// SetAnswer sets the "answer" edge to the Answers entity.
func (_c *AttemptAnswersCreate) SetAnswer(v *Answers) *AttemptAnswersCreate {
	return _c.SetAnswerID(v.ID)
}

// Mutation returns the AttemptAnswersMutation object of the builder.
func (_c *AttemptAnswersCreate) Mutation() *AttemptAnswersMutation {
	return _c.mutation
}

// Save creates the Attempt_answers in the database.
func (_c *AttemptAnswersCreate) Save(ctx context.Context) (*Attempt_answers, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AttemptAnswersCreate) SaveX(ctx context.Context) *Attempt_answers {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttemptAnswersCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttemptAnswersCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AttemptAnswersCreate) check() error {
	if len(_c.mutation.AttemptIDs()) == 0 {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required edge "Attempt_answers.attempt"`)}
	}
	if len(_c.mutation.QuestionIDs()) == 0 {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required edge "Attempt_answers.question"`)}
	}
	if len(_c.mutation.AnswerIDs()) == 0 {
		return &ValidationError{Name: "answer", err: errors.New(`ent: missing required edge "Attempt_answers.answer"`)}
	}
	return nil
}

func (_c *AttemptAnswersCreate) sqlSave(ctx context.Context) (*Attempt_answers, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AttemptAnswersCreate) createSpec() (*Attempt_answers, *sqlgraph.CreateSpec) {
	var (
		_node = &Attempt_answers{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(attempt_answers.Table, sqlgraph.NewFieldSpec(attempt_answers.FieldID, field.TypeInt))
	)
	if nodes := _c.mutation.AttemptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt_answers.AttemptTable,
			Columns: []string{attempt_answers.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.attempt_attempt_answers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.QuestionTable,
			Columns: []string{attempt_answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.attempt_answers_question = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnswerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.AnswerTable,
			Columns: []string{attempt_answers.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.attempt_answers_answer = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttemptAnswersCreateBulk is the builder for creating many Attempt_answers entities in bulk.
type AttemptAnswersCreateBulk struct {
	config
	err      error
	builders []*AttemptAnswersCreate
}

// Save creates the Attempt_answers entities in the database.
func (_c *AttemptAnswersCreateBulk) Save(ctx context.Context) ([]*Attempt_answers, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Attempt_answers, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttemptAnswersMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AttemptAnswersCreateBulk) SaveX(ctx context.Context) []*Attempt_answers {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttemptAnswersCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttemptAnswersCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
