// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"quizsystem/internal/store/ent/attempt_answers"
	"quizsystem/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttemptAnswersDelete is the builder for deleting a Attempt_answers entity.
type AttemptAnswersDelete struct {
	config
	hooks    []Hook
	mutation *AttemptAnswersMutation
}

// Where appends a list predicates to the AttemptAnswersDelete builder.
func (_d *AttemptAnswersDelete) Where(ps ...predicate.Attempt_answers) *AttemptAnswersDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AttemptAnswersDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AttemptAnswersDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AttemptAnswersDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(attempt_answers.Table, sqlgraph.NewFieldSpec(attempt_answers.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AttemptAnswersDeleteOne is the builder for deleting a single Attempt_answers entity.
type AttemptAnswersDeleteOne struct {
	_d *AttemptAnswersDelete
}

// Where appends a list predicates to the AttemptAnswersDelete builder.
func (_d *AttemptAnswersDeleteOne) Where(ps ...predicate.Attempt_answers) *AttemptAnswersDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AttemptAnswersDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attempt_answers.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AttemptAnswersDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
