// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/attempt"
	"quizsystem/internal/store/ent/attempt_answers"
	"quizsystem/internal/store/ent/predicate"
	"quizsystem/internal/store/ent/questions"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttemptAnswersUpdate is the builder for updating Attempt_answers entities.
type AttemptAnswersUpdate struct {
	config
	hooks    []Hook
	mutation *AttemptAnswersMutation
}

// Where appends a list predicates to the AttemptAnswersUpdate builder.
func (_u *AttemptAnswersUpdate) Where(ps ...predicate.Attempt_answers) *AttemptAnswersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAttemptID sets the "attempt" edge to the Attempt entity by ID.
func (_u *AttemptAnswersUpdate) SetAttemptID(id int) *AttemptAnswersUpdate {
	_u.mutation.SetAttemptID(id)
	return _u
}

// SetAttempt sets the "attempt" edge to the Attempt entity.
func (_u *AttemptAnswersUpdate) SetAttempt(v *Attempt) *AttemptAnswersUpdate {
	return _u.SetAttemptID(v.ID)
}

// SetQuestionID sets the "question" edge to the Questions entity by ID.
func (_u *AttemptAnswersUpdate) SetQuestionID(id int) *AttemptAnswersUpdate {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetQuestion sets the "question" edge to the Questions entity.
func (_u *AttemptAnswersUpdate) SetQuestion(v *Questions) *AttemptAnswersUpdate {
	return _u.SetQuestionID(v.ID)
}

// SetAnswerID sets the "answer" edge to the Answers entity by ID.
func (_u *AttemptAnswersUpdate) SetAnswerID(id int) *AttemptAnswersUpdate {
	_u.mutation.SetAnswerID(id)
	return _u
}

// SetAnswer sets the "answer" edge to the Answers entity.
func (_u *AttemptAnswersUpdate) SetAnswer(v *Answers) *AttemptAnswersUpdate {
	return _u.SetAnswerID(v.ID)
}

// Mutation returns the AttemptAnswersMutation object of the builder.
func (_u *AttemptAnswersUpdate) Mutation() *AttemptAnswersMutation {
	return _u.mutation
}

// ClearAttempt clears the "attempt" edge to the Attempt entity.
func (_u *AttemptAnswersUpdate) ClearAttempt() *AttemptAnswersUpdate {
	_u.mutation.ClearAttempt()
	return _u
}

// ClearQuestion clears the "question" edge to the Questions entity.
func (_u *AttemptAnswersUpdate) ClearQuestion() *AttemptAnswersUpdate {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearAnswer clears the "answer" edge to the Answers entity.
func (_u *AttemptAnswersUpdate) ClearAnswer() *AttemptAnswersUpdate {
	_u.mutation.ClearAnswer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AttemptAnswersUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttemptAnswersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AttemptAnswersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttemptAnswersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttemptAnswersUpdate) check() error {
	if _u.mutation.AttemptCleared() && len(_u.mutation.AttemptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attempt_answers.attempt"`)
	}
	if _u.mutation.QuestionCleared() && len(_u.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attempt_answers.question"`)
	}
	if _u.mutation.AnswerCleared() && len(_u.mutation.AnswerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attempt_answers.answer"`)
	}
	return nil
}

func (_u *AttemptAnswersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attempt_answers.Table, attempt_answers.Columns, sqlgraph.NewFieldSpec(attempt_answers.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AttemptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt_answers.AttemptTable,
			Columns: []string{attempt_answers.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt_answers.AttemptTable,
			Columns: []string{attempt_answers.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.QuestionTable,
			Columns: []string{attempt_answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.QuestionTable,
			Columns: []string{attempt_answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.AnswerTable,
			Columns: []string{attempt_answers.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.AnswerTable,
			Columns: []string{attempt_answers.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attempt_answers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AttemptAnswersUpdateOne is the builder for updating a single Attempt_answers entity.
type AttemptAnswersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttemptAnswersMutation
}

// SetAttemptID sets the "attempt" edge to the Attempt entity by ID.
func (_u *AttemptAnswersUpdateOne) SetAttemptID(id int) *AttemptAnswersUpdateOne {
	_u.mutation.SetAttemptID(id)
	return _u
}

// SetAttempt sets the "attempt" edge to the Attempt entity.
func (_u *AttemptAnswersUpdateOne) SetAttempt(v *Attempt) *AttemptAnswersUpdateOne {
	return _u.SetAttemptID(v.ID)
}

// SetQuestionID sets the "question" edge to the Questions entity by ID.
func (_u *AttemptAnswersUpdateOne) SetQuestionID(id int) *AttemptAnswersUpdateOne {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetQuestion sets the "question" edge to the Questions entity.
func (_u *AttemptAnswersUpdateOne) SetQuestion(v *Questions) *AttemptAnswersUpdateOne {
	return _u.SetQuestionID(v.ID)
}

// SetAnswerID sets the "answer" edge to the Answers entity by ID.
func (_u *AttemptAnswersUpdateOne) SetAnswerID(id int) *AttemptAnswersUpdateOne {
	_u.mutation.SetAnswerID(id)
	return _u
}

// SetAnswer sets the "answer" edge to the Answers entity.
func (_u *AttemptAnswersUpdateOne) SetAnswer(v *Answers) *AttemptAnswersUpdateOne {
	return _u.SetAnswerID(v.ID)
}

// Mutation returns the AttemptAnswersMutation object of the builder.
func (_u *AttemptAnswersUpdateOne) Mutation() *AttemptAnswersMutation {
	return _u.mutation
}

// ClearAttempt clears the "attempt" edge to the Attempt entity.
func (_u *AttemptAnswersUpdateOne) ClearAttempt() *AttemptAnswersUpdateOne {
	_u.mutation.ClearAttempt()
	return _u
}

// ClearQuestion clears the "question" edge to the Questions entity.
func (_u *AttemptAnswersUpdateOne) ClearQuestion() *AttemptAnswersUpdateOne {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearAnswer clears the "answer" edge to the Answers entity.
func (_u *AttemptAnswersUpdateOne) ClearAnswer() *AttemptAnswersUpdateOne {
	_u.mutation.ClearAnswer()
	return _u
}

// Where appends a list predicates to the AttemptAnswersUpdate builder.
func (_u *AttemptAnswersUpdateOne) Where(ps ...predicate.Attempt_answers) *AttemptAnswersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AttemptAnswersUpdateOne) Select(field string, fields ...string) *AttemptAnswersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Attempt_answers entity.
func (_u *AttemptAnswersUpdateOne) Save(ctx context.Context) (*Attempt_answers, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttemptAnswersUpdateOne) SaveX(ctx context.Context) *Attempt_answers {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AttemptAnswersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttemptAnswersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttemptAnswersUpdateOne) check() error {
	if _u.mutation.AttemptCleared() && len(_u.mutation.AttemptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attempt_answers.attempt"`)
	}
	if _u.mutation.QuestionCleared() && len(_u.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attempt_answers.question"`)
	}
	if _u.mutation.AnswerCleared() && len(_u.mutation.AnswerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attempt_answers.answer"`)
	}
	return nil
}

func (_u *AttemptAnswersUpdateOne) sqlSave(ctx context.Context) (_node *Attempt_answers, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attempt_answers.Table, attempt_answers.Columns, sqlgraph.NewFieldSpec(attempt_answers.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Attempt_answers.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attempt_answers.FieldID)
		for _, f := range fields {
			if !attempt_answers.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attempt_answers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AttemptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt_answers.AttemptTable,
			Columns: []string{attempt_answers.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attempt_answers.AttemptTable,
			Columns: []string{attempt_answers.AttemptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.QuestionTable,
			Columns: []string{attempt_answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.QuestionTable,
			Columns: []string{attempt_answers.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.AnswerTable,
			Columns: []string{attempt_answers.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attempt_answers.AnswerTable,
			Columns: []string{attempt_answers.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Attempt_answers{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attempt_answers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
