// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"quizsystem/internal/store/ent/migrate"

	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/attempt"
	"quizsystem/internal/store/ent/attempt_answers"
	"quizsystem/internal/store/ent/questions"
	"quizsystem/internal/store/ent/quiz"
	"quizsystem/internal/store/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Answers is the client for interacting with the Answers builders.
	Answers *AnswersClient
	// Attempt is the client for interacting with the Attempt builders.
	Attempt *AttemptClient
	// Attempt_answers is the client for interacting with the Attempt_answers builders.
	Attempt_answers *AttemptAnswersClient
	// Questions is the client for interacting with the Questions builders.
	Questions *QuestionsClient
	// Quiz is the client for interacting with the Quiz builders.
	Quiz *QuizClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Answers = NewAnswersClient(c.config)
	c.Attempt = NewAttemptClient(c.config)
	c.Attempt_answers = NewAttemptAnswersClient(c.config)
	c.Questions = NewQuestionsClient(c.config)
	c.Quiz = NewQuizClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Answers:         NewAnswersClient(cfg),
		Attempt:         NewAttemptClient(cfg),
		Attempt_answers: NewAttemptAnswersClient(cfg),
		Questions:       NewQuestionsClient(cfg),
		Quiz:            NewQuizClient(cfg),
		User:            NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Answers:         NewAnswersClient(cfg),
		Attempt:         NewAttemptClient(cfg),
		Attempt_answers: NewAttemptAnswersClient(cfg),
		Questions:       NewQuestionsClient(cfg),
		Quiz:            NewQuizClient(cfg),
		User:            NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Answers.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Answers, c.Attempt, c.Attempt_answers, c.Questions, c.Quiz, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Answers, c.Attempt, c.Attempt_answers, c.Questions, c.Quiz, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AnswersMutation:
		return c.Answers.mutate(ctx, m)
	case *AttemptMutation:
		return c.Attempt.mutate(ctx, m)
	case *AttemptAnswersMutation:
		return c.Attempt_answers.mutate(ctx, m)
	case *QuestionsMutation:
		return c.Questions.mutate(ctx, m)
	case *QuizMutation:
		return c.Quiz.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AnswersClient is a client for the Answers schema.
type AnswersClient struct {
	config
}

// NewAnswersClient returns a client for the Answers from the given config.
func NewAnswersClient(c config) *AnswersClient {
	return &AnswersClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `answers.Hooks(f(g(h())))`.
func (c *AnswersClient) Use(hooks ...Hook) {
	c.hooks.Answers = append(c.hooks.Answers, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `answers.Intercept(f(g(h())))`.
func (c *AnswersClient) Intercept(interceptors ...Interceptor) {
	c.inters.Answers = append(c.inters.Answers, interceptors...)
}

// Create returns a builder for creating a Answers entity.
func (c *AnswersClient) Create() *AnswersCreate {
	mutation := newAnswersMutation(c.config, OpCreate)
	return &AnswersCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Answers entities.
func (c *AnswersClient) CreateBulk(builders ...*AnswersCreate) *AnswersCreateBulk {
	return &AnswersCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AnswersClient) MapCreateBulk(slice any, setFunc func(*AnswersCreate, int)) *AnswersCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AnswersCreateBulk{err: fmt.Errorf("calling to AnswersClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AnswersCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AnswersCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Answers.
func (c *AnswersClient) Update() *AnswersUpdate {
	mutation := newAnswersMutation(c.config, OpUpdate)
	return &AnswersUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AnswersClient) UpdateOne(_m *Answers) *AnswersUpdateOne {
	mutation := newAnswersMutation(c.config, OpUpdateOne, withAnswers(_m))
	return &AnswersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AnswersClient) UpdateOneID(id int) *AnswersUpdateOne {
	mutation := newAnswersMutation(c.config, OpUpdateOne, withAnswersID(id))
	return &AnswersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Answers.
func (c *AnswersClient) Delete() *AnswersDelete {
	mutation := newAnswersMutation(c.config, OpDelete)
	return &AnswersDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AnswersClient) DeleteOne(_m *Answers) *AnswersDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AnswersClient) DeleteOneID(id int) *AnswersDeleteOne {
	builder := c.Delete().Where(answers.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AnswersDeleteOne{builder}
}

// Query returns a query builder for Answers.
func (c *AnswersClient) Query() *AnswersQuery {
	return &AnswersQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAnswers},
		inters: c.Interceptors(),
	}
}

// Get returns a Answers entity by its id.
func (c *AnswersClient) Get(ctx context.Context, id int) (*Answers, error) {
	return c.Query().Where(answers.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AnswersClient) GetX(ctx context.Context, id int) *Answers {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryQuestion queries the question edge of a Answers.
func (c *AnswersClient) QueryQuestion(_m *Answers) *QuestionsQuery {
	query := (&QuestionsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(answers.Table, answers.FieldID, id),
			sqlgraph.To(questions.Table, questions.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, answers.QuestionTable, answers.QuestionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AnswersClient) Hooks() []Hook {
	return c.hooks.Answers
}

// Interceptors returns the client interceptors.
func (c *AnswersClient) Interceptors() []Interceptor {
	return c.inters.Answers
}

func (c *AnswersClient) mutate(ctx context.Context, m *AnswersMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AnswersCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AnswersUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AnswersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AnswersDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Answers mutation op: %q", m.Op())
	}
}

// AttemptClient is a client for the Attempt schema.
type AttemptClient struct {
	config
}

// NewAttemptClient returns a client for the Attempt from the given config.
func NewAttemptClient(c config) *AttemptClient {
	return &AttemptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `attempt.Hooks(f(g(h())))`.
func (c *AttemptClient) Use(hooks ...Hook) {
	c.hooks.Attempt = append(c.hooks.Attempt, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `attempt.Intercept(f(g(h())))`.
func (c *AttemptClient) Intercept(interceptors ...Interceptor) {
	c.inters.Attempt = append(c.inters.Attempt, interceptors...)
}

// Create returns a builder for creating a Attempt entity.
func (c *AttemptClient) Create() *AttemptCreate {
	mutation := newAttemptMutation(c.config, OpCreate)
	return &AttemptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Attempt entities.
func (c *AttemptClient) CreateBulk(builders ...*AttemptCreate) *AttemptCreateBulk {
	return &AttemptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AttemptClient) MapCreateBulk(slice any, setFunc func(*AttemptCreate, int)) *AttemptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AttemptCreateBulk{err: fmt.Errorf("calling to AttemptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AttemptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AttemptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Attempt.
func (c *AttemptClient) Update() *AttemptUpdate {
	mutation := newAttemptMutation(c.config, OpUpdate)
	return &AttemptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AttemptClient) UpdateOne(_m *Attempt) *AttemptUpdateOne {
	mutation := newAttemptMutation(c.config, OpUpdateOne, withAttempt(_m))
	return &AttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AttemptClient) UpdateOneID(id int) *AttemptUpdateOne {
	mutation := newAttemptMutation(c.config, OpUpdateOne, withAttemptID(id))
	return &AttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Attempt.
func (c *AttemptClient) Delete() *AttemptDelete {
	mutation := newAttemptMutation(c.config, OpDelete)
	return &AttemptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AttemptClient) DeleteOne(_m *Attempt) *AttemptDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AttemptClient) DeleteOneID(id int) *AttemptDeleteOne {
	builder := c.Delete().Where(attempt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AttemptDeleteOne{builder}
}

// Query returns a query builder for Attempt.
func (c *AttemptClient) Query() *AttemptQuery {
	return &AttemptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAttempt},
		inters: c.Interceptors(),
	}
}

// Get returns a Attempt entity by its id.
func (c *AttemptClient) Get(ctx context.Context, id int) (*Attempt, error) {
	return c.Query().Where(attempt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AttemptClient) GetX(ctx context.Context, id int) *Attempt {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Attempt.
func (c *AttemptClient) QueryUser(_m *Attempt) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attempt.Table, attempt.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attempt.UserTable, attempt.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryQuiz queries the quiz edge of a Attempt.
func (c *AttemptClient) QueryQuiz(_m *Attempt) *QuizQuery {
	query := (&QuizClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attempt.Table, attempt.FieldID, id),
			sqlgraph.To(quiz.Table, quiz.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attempt.QuizTable, attempt.QuizColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAttemptAnswers queries the attempt_answers edge of a Attempt.
func (c *AttemptClient) QueryAttemptAnswers(_m *Attempt) *AttemptAnswersQuery {
	query := (&AttemptAnswersClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attempt.Table, attempt.FieldID, id),
			sqlgraph.To(attempt_answers.Table, attempt_answers.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, attempt.AttemptAnswersTable, attempt.AttemptAnswersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AttemptClient) Hooks() []Hook {
	return c.hooks.Attempt
}

// Interceptors returns the client interceptors.
func (c *AttemptClient) Interceptors() []Interceptor {
	return c.inters.Attempt
}

func (c *AttemptClient) mutate(ctx context.Context, m *AttemptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AttemptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AttemptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AttemptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AttemptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Attempt mutation op: %q", m.Op())
	}
}

// AttemptAnswersClient is a client for the Attempt_answers schema.
type AttemptAnswersClient struct {
	config
}

// NewAttemptAnswersClient returns a client for the Attempt_answers from the given config.
func NewAttemptAnswersClient(c config) *AttemptAnswersClient {
	return &AttemptAnswersClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `attempt_answers.Hooks(f(g(h())))`.
func (c *AttemptAnswersClient) Use(hooks ...Hook) {
	c.hooks.Attempt_answers = append(c.hooks.Attempt_answers, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `attempt_answers.Intercept(f(g(h())))`.
func (c *AttemptAnswersClient) Intercept(interceptors ...Interceptor) {
	c.inters.Attempt_answers = append(c.inters.Attempt_answers, interceptors...)
}

// Create returns a builder for creating a Attempt_answers entity.
func (c *AttemptAnswersClient) Create() *AttemptAnswersCreate {
	mutation := newAttemptAnswersMutation(c.config, OpCreate)
	return &AttemptAnswersCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Attempt_answers entities.
func (c *AttemptAnswersClient) CreateBulk(builders ...*AttemptAnswersCreate) *AttemptAnswersCreateBulk {
	return &AttemptAnswersCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AttemptAnswersClient) MapCreateBulk(slice any, setFunc func(*AttemptAnswersCreate, int)) *AttemptAnswersCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AttemptAnswersCreateBulk{err: fmt.Errorf("calling to AttemptAnswersClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AttemptAnswersCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AttemptAnswersCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Attempt_answers.
func (c *AttemptAnswersClient) Update() *AttemptAnswersUpdate {
	mutation := newAttemptAnswersMutation(c.config, OpUpdate)
	return &AttemptAnswersUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AttemptAnswersClient) UpdateOne(_m *Attempt_answers) *AttemptAnswersUpdateOne {
	mutation := newAttemptAnswersMutation(c.config, OpUpdateOne, withAttempt_answers(_m))
	return &AttemptAnswersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AttemptAnswersClient) UpdateOneID(id int) *AttemptAnswersUpdateOne {
	mutation := newAttemptAnswersMutation(c.config, OpUpdateOne, withAttempt_answersID(id))
	return &AttemptAnswersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Attempt_answers.
func (c *AttemptAnswersClient) Delete() *AttemptAnswersDelete {
	mutation := newAttemptAnswersMutation(c.config, OpDelete)
	return &AttemptAnswersDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AttemptAnswersClient) DeleteOne(_m *Attempt_answers) *AttemptAnswersDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AttemptAnswersClient) DeleteOneID(id int) *AttemptAnswersDeleteOne {
	builder := c.Delete().Where(attempt_answers.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AttemptAnswersDeleteOne{builder}
}

// Query returns a query builder for Attempt_answers.
func (c *AttemptAnswersClient) Query() *AttemptAnswersQuery {
	return &AttemptAnswersQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAttemptAnswers},
		inters: c.Interceptors(),
	}
}

// Get returns a Attempt_answers entity by its id.
func (c *AttemptAnswersClient) Get(ctx context.Context, id int) (*Attempt_answers, error) {
	return c.Query().Where(attempt_answers.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AttemptAnswersClient) GetX(ctx context.Context, id int) *Attempt_answers {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAttempt queries the attempt edge of a Attempt_answers.
func (c *AttemptAnswersClient) QueryAttempt(_m *Attempt_answers) *AttemptQuery {
	query := (&AttemptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attempt_answers.Table, attempt_answers.FieldID, id),
			sqlgraph.To(attempt.Table, attempt.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attempt_answers.AttemptTable, attempt_answers.AttemptColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryQuestion queries the question edge of a Attempt_answers.
func (c *AttemptAnswersClient) QueryQuestion(_m *Attempt_answers) *QuestionsQuery {
	query := (&QuestionsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attempt_answers.Table, attempt_answers.FieldID, id),
			sqlgraph.To(questions.Table, questions.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, attempt_answers.QuestionTable, attempt_answers.QuestionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAnswer queries the answer edge of a Attempt_answers.
func (c *AttemptAnswersClient) QueryAnswer(_m *Attempt_answers) *AnswersQuery {
	query := (&AnswersClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attempt_answers.Table, attempt_answers.FieldID, id),
			sqlgraph.To(answers.Table, answers.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, attempt_answers.AnswerTable, attempt_answers.AnswerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AttemptAnswersClient) Hooks() []Hook {
	return c.hooks.Attempt_answers
}

// Interceptors returns the client interceptors.
func (c *AttemptAnswersClient) Interceptors() []Interceptor {
	return c.inters.Attempt_answers
}

func (c *AttemptAnswersClient) mutate(ctx context.Context, m *AttemptAnswersMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AttemptAnswersCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AttemptAnswersUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AttemptAnswersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AttemptAnswersDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Attempt_answers mutation op: %q", m.Op())
	}
}

// QuestionsClient is a client for the Questions schema.
type QuestionsClient struct {
	config
}

// NewQuestionsClient returns a client for the Questions from the given config.
func NewQuestionsClient(c config) *QuestionsClient {
	return &QuestionsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `questions.Hooks(f(g(h())))`.
func (c *QuestionsClient) Use(hooks ...Hook) {
	c.hooks.Questions = append(c.hooks.Questions, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `questions.Intercept(f(g(h())))`.
func (c *QuestionsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Questions = append(c.inters.Questions, interceptors...)
}

// Create returns a builder for creating a Questions entity.
func (c *QuestionsClient) Create() *QuestionsCreate {
	mutation := newQuestionsMutation(c.config, OpCreate)
	return &QuestionsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Questions entities.
func (c *QuestionsClient) CreateBulk(builders ...*QuestionsCreate) *QuestionsCreateBulk {
	return &QuestionsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *QuestionsClient) MapCreateBulk(slice any, setFunc func(*QuestionsCreate, int)) *QuestionsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &QuestionsCreateBulk{err: fmt.Errorf("calling to QuestionsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*QuestionsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &QuestionsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Questions.
func (c *QuestionsClient) Update() *QuestionsUpdate {
	mutation := newQuestionsMutation(c.config, OpUpdate)
	return &QuestionsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *QuestionsClient) UpdateOne(_m *Questions) *QuestionsUpdateOne {
	mutation := newQuestionsMutation(c.config, OpUpdateOne, withQuestions(_m))
	return &QuestionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *QuestionsClient) UpdateOneID(id int) *QuestionsUpdateOne {
	mutation := newQuestionsMutation(c.config, OpUpdateOne, withQuestionsID(id))
	return &QuestionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Questions.
func (c *QuestionsClient) Delete() *QuestionsDelete {
	mutation := newQuestionsMutation(c.config, OpDelete)
	return &QuestionsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *QuestionsClient) DeleteOne(_m *Questions) *QuestionsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *QuestionsClient) DeleteOneID(id int) *QuestionsDeleteOne {
	builder := c.Delete().Where(questions.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &QuestionsDeleteOne{builder}
}

// Query returns a query builder for Questions.
func (c *QuestionsClient) Query() *QuestionsQuery {
	return &QuestionsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeQuestions},
		inters: c.Interceptors(),
	}
}

// Get returns a Questions entity by its id.
func (c *QuestionsClient) Get(ctx context.Context, id int) (*Questions, error) {
	return c.Query().Where(questions.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *QuestionsClient) GetX(ctx context.Context, id int) *Questions {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryQuiz queries the quiz edge of a Questions.
func (c *QuestionsClient) QueryQuiz(_m *Questions) *QuizQuery {
	query := (&QuizClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(questions.Table, questions.FieldID, id),
			sqlgraph.To(quiz.Table, quiz.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, questions.QuizTable, questions.QuizColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAnswers queries the answers edge of a Questions.
func (c *QuestionsClient) QueryAnswers(_m *Questions) *AnswersQuery {
	query := (&AnswersClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(questions.Table, questions.FieldID, id),
			sqlgraph.To(answers.Table, answers.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, questions.AnswersTable, questions.AnswersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *QuestionsClient) Hooks() []Hook {
	return c.hooks.Questions
}

// Interceptors returns the client interceptors.
func (c *QuestionsClient) Interceptors() []Interceptor {
	return c.inters.Questions
}

func (c *QuestionsClient) mutate(ctx context.Context, m *QuestionsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&QuestionsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&QuestionsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&QuestionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&QuestionsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Questions mutation op: %q", m.Op())
	}
}

// QuizClient is a client for the Quiz schema.
type QuizClient struct {
	config
}

// NewQuizClient returns a client for the Quiz from the given config.
func NewQuizClient(c config) *QuizClient {
	return &QuizClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `quiz.Hooks(f(g(h())))`.
func (c *QuizClient) Use(hooks ...Hook) {
	c.hooks.Quiz = append(c.hooks.Quiz, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `quiz.Intercept(f(g(h())))`.
func (c *QuizClient) Intercept(interceptors ...Interceptor) {
	c.inters.Quiz = append(c.inters.Quiz, interceptors...)
}

// Create returns a builder for creating a Quiz entity.
func (c *QuizClient) Create() *QuizCreate {
	mutation := newQuizMutation(c.config, OpCreate)
	return &QuizCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Quiz entities.
func (c *QuizClient) CreateBulk(builders ...*QuizCreate) *QuizCreateBulk {
	return &QuizCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *QuizClient) MapCreateBulk(slice any, setFunc func(*QuizCreate, int)) *QuizCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &QuizCreateBulk{err: fmt.Errorf("calling to QuizClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*QuizCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &QuizCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Quiz.
func (c *QuizClient) Update() *QuizUpdate {
	mutation := newQuizMutation(c.config, OpUpdate)
	return &QuizUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *QuizClient) UpdateOne(_m *Quiz) *QuizUpdateOne {
	mutation := newQuizMutation(c.config, OpUpdateOne, withQuiz(_m))
	return &QuizUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *QuizClient) UpdateOneID(id int) *QuizUpdateOne {
	mutation := newQuizMutation(c.config, OpUpdateOne, withQuizID(id))
	return &QuizUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Quiz.
func (c *QuizClient) Delete() *QuizDelete {
	mutation := newQuizMutation(c.config, OpDelete)
	return &QuizDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *QuizClient) DeleteOne(_m *Quiz) *QuizDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *QuizClient) DeleteOneID(id int) *QuizDeleteOne {
	builder := c.Delete().Where(quiz.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &QuizDeleteOne{builder}
}

// Query returns a query builder for Quiz.
func (c *QuizClient) Query() *QuizQuery {
	return &QuizQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeQuiz},
		inters: c.Interceptors(),
	}
}

// Get returns a Quiz entity by its id.
func (c *QuizClient) Get(ctx context.Context, id int) (*Quiz, error) {
	return c.Query().Where(quiz.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *QuizClient) GetX(ctx context.Context, id int) *Quiz {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCreator queries the creator edge of a Quiz.
func (c *QuizClient) QueryCreator(_m *Quiz) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(quiz.Table, quiz.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, quiz.CreatorTable, quiz.CreatorColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryQuestions queries the questions edge of a Quiz.
func (c *QuizClient) QueryQuestions(_m *Quiz) *QuestionsQuery {
	query := (&QuestionsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(quiz.Table, quiz.FieldID, id),
			sqlgraph.To(questions.Table, questions.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, quiz.QuestionsTable, quiz.QuestionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAttempts queries the attempts edge of a Quiz.
func (c *QuizClient) QueryAttempts(_m *Quiz) *AttemptQuery {
	query := (&AttemptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(quiz.Table, quiz.FieldID, id),
			sqlgraph.To(attempt.Table, attempt.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, quiz.AttemptsTable, quiz.AttemptsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *QuizClient) Hooks() []Hook {
	return c.hooks.Quiz
}

// Interceptors returns the client interceptors.
func (c *QuizClient) Interceptors() []Interceptor {
	return c.inters.Quiz
}

func (c *QuizClient) mutate(ctx context.Context, m *QuizMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&QuizCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&QuizUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&QuizUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&QuizDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Quiz mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAttempts queries the attempts edge of a User.
func (c *UserClient) QueryAttempts(_m *User) *AttemptQuery {
	query := (&AttemptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(attempt.Table, attempt.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.AttemptsTable, user.AttemptsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryQuizzes queries the quizzes edge of a User.
func (c *UserClient) QueryQuizzes(_m *User) *QuizQuery {
	query := (&QuizClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(quiz.Table, quiz.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.QuizzesTable, user.QuizzesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Answers, Attempt, Attempt_answers, Questions, Quiz, User []ent.Hook
	}
	inters struct {
		Answers, Attempt, Attempt_answers, Questions, Quiz, User []ent.Interceptor
	}
)
