// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/questions"
	"quizsystem/internal/store/ent/quiz"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionsCreate is the builder for creating a Questions entity.
type QuestionsCreate struct {
	config
	mutation *QuestionsMutation
	hooks    []Hook
}

// SetText sets the "text" field.
func (_c *QuestionsCreate) SetText(v string) *QuestionsCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetOrderIndex sets the "order_index" field.
func (_c *QuestionsCreate) SetOrderIndex(v int) *QuestionsCreate {
	_c.mutation.SetOrderIndex(v)
	return _c
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_c *QuestionsCreate) SetQuizID(id int) *QuestionsCreate {
	_c.mutation.SetQuizID(id)
	return _c
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_c *QuestionsCreate) SetQuiz(v *Quiz) *QuestionsCreate {
	return _c.SetQuizID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the Answers entity by IDs.
func (_c *QuestionsCreate) AddAnswerIDs(ids ...int) *QuestionsCreate {
	_c.mutation.AddAnswerIDs(ids...)
	return _c
}

// AddAnswers adds the "answers" edges to the Answers entity.
func (_c *QuestionsCreate) AddAnswers(v ...*Answers) *QuestionsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnswerIDs(ids...)
}

// Mutation returns the QuestionsMutation object of the builder.
func (_c *QuestionsCreate) Mutation() *QuestionsMutation {
	return _c.mutation
}

// Save creates the Questions in the database.
func (_c *QuestionsCreate) Save(ctx context.Context) (*Questions, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuestionsCreate) SaveX(ctx context.Context) *Questions {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestionsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestionsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuestionsCreate) check() error {
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Questions.text"`)}
	}
	if _, ok := _c.mutation.OrderIndex(); !ok {
		return &ValidationError{Name: "order_index", err: errors.New(`ent: missing required field "Questions.order_index"`)}
	}
	if len(_c.mutation.QuizIDs()) == 0 {
		return &ValidationError{Name: "quiz", err: errors.New(`ent: missing required edge "Questions.quiz"`)}
	}
	return nil
}

func (_c *QuestionsCreate) sqlSave(ctx context.Context) (*Questions, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuestionsCreate) createSpec() (*Questions, *sqlgraph.CreateSpec) {
	var (
		_node = &Questions{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(questions.Table, sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(questions.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.OrderIndex(); ok {
		_spec.SetField(questions.FieldOrderIndex, field.TypeInt, value)
		_node.OrderIndex = value
	}
	if nodes := _c.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questions.QuizTable,
			Columns: []string{questions.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.quiz_questions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questions.AnswersTable,
			Columns: []string{questions.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuestionsCreateBulk is the builder for creating many Questions entities in bulk.
type QuestionsCreateBulk struct {
	config
	err      error
	builders []*QuestionsCreate
}

// Save creates the Questions entities in the database.
func (_c *QuestionsCreateBulk) Save(ctx context.Context) ([]*Questions, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Questions, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuestionsCreateBulk) SaveX(ctx context.Context) []*Questions {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestionsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestionsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
