// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/predicate"
	"quizsystem/internal/store/ent/questions"
	"quizsystem/internal/store/ent/quiz"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionsUpdate is the builder for updating Questions entities.
type QuestionsUpdate struct {
	config
	hooks    []Hook
	mutation *QuestionsMutation
}

// Where appends a list predicates to the QuestionsUpdate builder.
func (_u *QuestionsUpdate) Where(ps ...predicate.Questions) *QuestionsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *QuestionsUpdate) SetText(v string) *QuestionsUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *QuestionsUpdate) SetNillableText(v *string) *QuestionsUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *QuestionsUpdate) SetOrderIndex(v int) *QuestionsUpdate {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *QuestionsUpdate) SetNillableOrderIndex(v *int) *QuestionsUpdate {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *QuestionsUpdate) AddOrderIndex(v int) *QuestionsUpdate {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_u *QuestionsUpdate) SetQuizID(id int) *QuestionsUpdate {
	_u.mutation.SetQuizID(id)
	return _u
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_u *QuestionsUpdate) SetQuiz(v *Quiz) *QuestionsUpdate {
	return _u.SetQuizID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the Answers entity by IDs.
func (_u *QuestionsUpdate) AddAnswerIDs(ids ...int) *QuestionsUpdate {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answers entity.
func (_u *QuestionsUpdate) AddAnswers(v ...*Answers) *QuestionsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// Mutation returns the QuestionsMutation object of the builder.
func (_u *QuestionsUpdate) Mutation() *QuestionsMutation {
	return _u.mutation
}

// ClearQuiz clears the "quiz" edge to the Quiz entity.
func (_u *QuestionsUpdate) ClearQuiz() *QuestionsUpdate {
	_u.mutation.ClearQuiz()
	return _u
}

// ClearAnswers clears all "answers" edges to the Answers entity.
func (_u *QuestionsUpdate) ClearAnswers() *QuestionsUpdate {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answers entities by IDs.
func (_u *QuestionsUpdate) RemoveAnswerIDs(ids ...int) *QuestionsUpdate {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answers entities.
func (_u *QuestionsUpdate) RemoveAnswers(v ...*Answers) *QuestionsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuestionsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestionsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuestionsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestionsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuestionsUpdate) check() error {
	if _u.mutation.QuizCleared() && len(_u.mutation.QuizIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Questions.quiz"`)
	}
	return nil
}

func (_u *QuestionsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(questions.Table, questions.Columns, sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(questions.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(questions.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(questions.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.QuizCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questions.QuizTable,
			Columns: []string{questions.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questions.QuizTable,
			Columns: []string{questions.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questions.AnswersTable,
			Columns: []string{questions.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questions.AnswersTable,
			Columns: []string{questions.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questions.AnswersTable,
			Columns: []string{questions.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{questions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuestionsUpdateOne is the builder for updating a single Questions entity.
type QuestionsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuestionsMutation
}

// SetText sets the "text" field.
func (_u *QuestionsUpdateOne) SetText(v string) *QuestionsUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *QuestionsUpdateOne) SetNillableText(v *string) *QuestionsUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *QuestionsUpdateOne) SetOrderIndex(v int) *QuestionsUpdateOne {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *QuestionsUpdateOne) SetNillableOrderIndex(v *int) *QuestionsUpdateOne {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *QuestionsUpdateOne) AddOrderIndex(v int) *QuestionsUpdateOne {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_u *QuestionsUpdateOne) SetQuizID(id int) *QuestionsUpdateOne {
	_u.mutation.SetQuizID(id)
	return _u
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_u *QuestionsUpdateOne) SetQuiz(v *Quiz) *QuestionsUpdateOne {
	return _u.SetQuizID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the Answers entity by IDs.
func (_u *QuestionsUpdateOne) AddAnswerIDs(ids ...int) *QuestionsUpdateOne {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answers entity.
func (_u *QuestionsUpdateOne) AddAnswers(v ...*Answers) *QuestionsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// Mutation returns the QuestionsMutation object of the builder.
func (_u *QuestionsUpdateOne) Mutation() *QuestionsMutation {
	return _u.mutation
}

// ClearQuiz clears the "quiz" edge to the Quiz entity.
func (_u *QuestionsUpdateOne) ClearQuiz() *QuestionsUpdateOne {
	_u.mutation.ClearQuiz()
	return _u
}

// ClearAnswers clears all "answers" edges to the Answers entity.
func (_u *QuestionsUpdateOne) ClearAnswers() *QuestionsUpdateOne {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answers entities by IDs.
func (_u *QuestionsUpdateOne) RemoveAnswerIDs(ids ...int) *QuestionsUpdateOne {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answers entities.
func (_u *QuestionsUpdateOne) RemoveAnswers(v ...*Answers) *QuestionsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// Where appends a list predicates to the QuestionsUpdate builder.
func (_u *QuestionsUpdateOne) Where(ps ...predicate.Questions) *QuestionsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuestionsUpdateOne) Select(field string, fields ...string) *QuestionsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Questions entity.
func (_u *QuestionsUpdateOne) Save(ctx context.Context) (*Questions, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestionsUpdateOne) SaveX(ctx context.Context) *Questions {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuestionsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestionsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuestionsUpdateOne) check() error {
	if _u.mutation.QuizCleared() && len(_u.mutation.QuizIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Questions.quiz"`)
	}
	return nil
}

func (_u *QuestionsUpdateOne) sqlSave(ctx context.Context) (_node *Questions, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(questions.Table, questions.Columns, sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Questions.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, questions.FieldID)
		for _, f := range fields {
			if !questions.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != questions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(questions.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(questions.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(questions.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.QuizCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questions.QuizTable,
			Columns: []string{questions.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questions.QuizTable,
			Columns: []string{questions.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questions.AnswersTable,
			Columns: []string{questions.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questions.AnswersTable,
			Columns: []string{questions.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questions.AnswersTable,
			Columns: []string{questions.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Questions{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{questions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
