// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"quizsystem/internal/store/ent/questions"
	"quizsystem/internal/store/ent/quiz"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Questions is the model entity for the Questions schema.
type Questions struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// OrderIndex holds the value of the "order_index" field.
	OrderIndex int `json:"order_index,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QuestionsQuery when eager-loading is set.
	Edges          QuestionsEdges `json:"edges"`
	quiz_questions *int
	selectValues   sql.SelectValues
}

// QuestionsEdges holds the relations/edges for other nodes in the graph.
type QuestionsEdges struct {
	// Quiz holds the value of the quiz edge.
	Quiz *Quiz `json:"quiz,omitempty"`
	// Answers holds the value of the answers edge.
	Answers []*Answers `json:"answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// QuizOrErr returns the Quiz value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QuestionsEdges) QuizOrErr() (*Quiz, error) {
	if e.Quiz != nil {
		return e.Quiz, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: quiz.Label}
	}
	return nil, &NotLoadedError{edge: "quiz"}
}

// AnswersOrErr returns the Answers value or an error if the edge
// was not loaded in eager-loading.
func (e QuestionsEdges) AnswersOrErr() ([]*Answers, error) {
	if e.loadedTypes[1] {
		return e.Answers, nil
	}
	return nil, &NotLoadedError{edge: "answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Questions) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case questions.FieldID, questions.FieldOrderIndex:
			values[i] = new(sql.NullInt64)
		case questions.FieldText:
			values[i] = new(sql.NullString)
		case questions.ForeignKeys[0]: // quiz_questions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Questions fields.
func (_m *Questions) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case questions.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case questions.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case questions.FieldOrderIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_index", values[i])
			} else if value.Valid {
				_m.OrderIndex = int(value.Int64)
			}
		case questions.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field quiz_questions", value)
			} else if value.Valid {
				_m.quiz_questions = new(int)
				*_m.quiz_questions = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Questions.
// This includes values selected through modifiers, order, etc.
func (_m *Questions) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuiz queries the "quiz" edge of the Questions entity.
func (_m *Questions) QueryQuiz() *QuizQuery {
	return NewQuestionsClient(_m.config).QueryQuiz(_m)
}

// QueryAnswers queries the "answers" edge of the Questions entity.
func (_m *Questions) QueryAnswers() *AnswersQuery {
	return NewQuestionsClient(_m.config).QueryAnswers(_m)
}

// Update returns a builder for updating this Questions.
// Note that you need to call Questions.Unwrap() before calling this method if this Questions
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Questions) Update() *QuestionsUpdateOne {
	return NewQuestionsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Questions entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Questions) Unwrap() *Questions {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Questions is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Questions) String() string {
	var builder strings.Builder
	builder.WriteString("Questions(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("order_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderIndex))
	builder.WriteByte(')')
	return builder.String()
}

// QuestionsSlice is a parsable slice of Questions.
type QuestionsSlice []*Questions
