// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"quizsystem/internal/store/ent/attempt"
	"quizsystem/internal/store/ent/predicate"
	"quizsystem/internal/store/ent/questions"
	"quizsystem/internal/store/ent/quiz"
	"quizsystem/internal/store/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizUpdate is the builder for updating Quiz entities.
type QuizUpdate struct {
	config
	hooks    []Hook
	mutation *QuizMutation
}

// Where appends a list predicates to the QuizUpdate builder.
func (_u *QuizUpdate) Where(ps ...predicate.Quiz) *QuizUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *QuizUpdate) SetTitle(v string) *QuizUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *QuizUpdate) SetNillableTitle(v *string) *QuizUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *QuizUpdate) SetIsPublished(v bool) *QuizUpdate {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *QuizUpdate) SetNillableIsPublished(v *bool) *QuizUpdate {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetPassThreshold sets the "pass_threshold" field.
func (_u *QuizUpdate) SetPassThreshold(v int) *QuizUpdate {
	_u.mutation.ResetPassThreshold()
	_u.mutation.SetPassThreshold(v)
	return _u
}

// SetNillablePassThreshold sets the "pass_threshold" field if the given value is not nil.
func (_u *QuizUpdate) SetNillablePassThreshold(v *int) *QuizUpdate {
	if v != nil {
		_u.SetPassThreshold(*v)
	}
	return _u
}

// AddPassThreshold adds value to the "pass_threshold" field.
func (_u *QuizUpdate) AddPassThreshold(v int) *QuizUpdate {
	_u.mutation.AddPassThreshold(v)
	return _u
}

// ClearPassThreshold clears the value of the "pass_threshold" field.
func (_u *QuizUpdate) ClearPassThreshold() *QuizUpdate {
	_u.mutation.ClearPassThreshold()
	return _u
}

// SetOneAttempt sets the "one_attempt" field.
func (_u *QuizUpdate) SetOneAttempt(v bool) *QuizUpdate {
	_u.mutation.SetOneAttempt(v)
	return _u
}

// SetNillableOneAttempt sets the "one_attempt" field if the given value is not nil.
func (_u *QuizUpdate) SetNillableOneAttempt(v *bool) *QuizUpdate {
	if v != nil {
		_u.SetOneAttempt(*v)
	}
	return _u
}

// SetShowAnswers sets the "show_answers" field.
func (_u *QuizUpdate) SetShowAnswers(v bool) *QuizUpdate {
	_u.mutation.SetShowAnswers(v)
	return _u
}

// SetNillableShowAnswers sets the "show_answers" field if the given value is not nil.
func (_u *QuizUpdate) SetNillableShowAnswers(v *bool) *QuizUpdate {
	if v != nil {
		_u.SetShowAnswers(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *QuizUpdate) SetCreatedAt(v time.Time) *QuizUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *QuizUpdate) SetNillableCreatedAt(v *time.Time) *QuizUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *QuizUpdate) SetCreatorID(id int) *QuizUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *QuizUpdate) SetCreator(v *User) *QuizUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddQuestionIDs adds the "questions" edge to the Questions entity by IDs.
func (_u *QuizUpdate) AddQuestionIDs(ids ...int) *QuizUpdate {
	_u.mutation.AddQuestionIDs(ids...)
	return _u
}

// AddQuestions adds the "questions" edges to the Questions entity.
func (_u *QuizUpdate) AddQuestions(v ...*Questions) *QuizUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestionIDs(ids...)
}

// AddAttemptIDs adds the "attempts" edge to the Attempt entity by IDs.
func (_u *QuizUpdate) AddAttemptIDs(ids ...int) *QuizUpdate {
	_u.mutation.AddAttemptIDs(ids...)
	return _u
}

// AddAttempts adds the "attempts" edges to the Attempt entity.
func (_u *QuizUpdate) AddAttempts(v ...*Attempt) *QuizUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptIDs(ids...)
}

// Mutation returns the QuizMutation object of the builder.
func (_u *QuizUpdate) Mutation() *QuizMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *QuizUpdate) ClearCreator() *QuizUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearQuestions clears all "questions" edges to the Questions entity.
func (_u *QuizUpdate) ClearQuestions() *QuizUpdate {
	_u.mutation.ClearQuestions()
	return _u
}

// RemoveQuestionIDs removes the "questions" edge to Questions entities by IDs.
func (_u *QuizUpdate) RemoveQuestionIDs(ids ...int) *QuizUpdate {
	_u.mutation.RemoveQuestionIDs(ids...)
	return _u
}

// RemoveQuestions removes "questions" edges to Questions entities.
func (_u *QuizUpdate) RemoveQuestions(v ...*Questions) *QuizUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestionIDs(ids...)
}

// ClearAttempts clears all "attempts" edges to the Attempt entity.
func (_u *QuizUpdate) ClearAttempts() *QuizUpdate {
	_u.mutation.ClearAttempts()
	return _u
}

// RemoveAttemptIDs removes the "attempts" edge to Attempt entities by IDs.
func (_u *QuizUpdate) RemoveAttemptIDs(ids ...int) *QuizUpdate {
	_u.mutation.RemoveAttemptIDs(ids...)
	return _u
}

// RemoveAttempts removes "attempts" edges to Attempt entities.
func (_u *QuizUpdate) RemoveAttempts(v ...*Attempt) *QuizUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuizUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuizUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizUpdate) check() error {
	if v, ok := _u.mutation.PassThreshold(); ok {
		if err := quiz.PassThresholdValidator(v); err != nil {
			return &ValidationError{Name: "pass_threshold", err: fmt.Errorf(`ent: validator failed for field "Quiz.pass_threshold": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Quiz.creator"`)
	}
	return nil
}

func (_u *QuizUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quiz.Table, quiz.Columns, sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(quiz.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(quiz.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PassThreshold(); ok {
		_spec.SetField(quiz.FieldPassThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassThreshold(); ok {
		_spec.AddField(quiz.FieldPassThreshold, field.TypeInt, value)
	}
	if _u.mutation.PassThresholdCleared() {
		_spec.ClearField(quiz.FieldPassThreshold, field.TypeInt)
	}
	if value, ok := _u.mutation.OneAttempt(); ok {
		_spec.SetField(quiz.FieldOneAttempt, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShowAnswers(); ok {
		_spec.SetField(quiz.FieldShowAnswers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(quiz.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.CreatorTable,
			Columns: []string{quiz.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.CreatorTable,
			Columns: []string{quiz.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestionsIDs(); len(nodes) > 0 && !_u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptsIDs(); len(nodes) > 0 && !_u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quiz.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuizUpdateOne is the builder for updating a single Quiz entity.
type QuizUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuizMutation
}

// SetTitle sets the "title" field.
func (_u *QuizUpdateOne) SetTitle(v string) *QuizUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *QuizUpdateOne) SetNillableTitle(v *string) *QuizUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *QuizUpdateOne) SetIsPublished(v bool) *QuizUpdateOne {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *QuizUpdateOne) SetNillableIsPublished(v *bool) *QuizUpdateOne {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetPassThreshold sets the "pass_threshold" field.
func (_u *QuizUpdateOne) SetPassThreshold(v int) *QuizUpdateOne {
	_u.mutation.ResetPassThreshold()
	_u.mutation.SetPassThreshold(v)
	return _u
}

// SetNillablePassThreshold sets the "pass_threshold" field if the given value is not nil.
func (_u *QuizUpdateOne) SetNillablePassThreshold(v *int) *QuizUpdateOne {
	if v != nil {
		_u.SetPassThreshold(*v)
	}
	return _u
}

// AddPassThreshold adds value to the "pass_threshold" field.
func (_u *QuizUpdateOne) AddPassThreshold(v int) *QuizUpdateOne {
	_u.mutation.AddPassThreshold(v)
	return _u
}

// ClearPassThreshold clears the value of the "pass_threshold" field.
func (_u *QuizUpdateOne) ClearPassThreshold() *QuizUpdateOne {
	_u.mutation.ClearPassThreshold()
	return _u
}

// SetOneAttempt sets the "one_attempt" field.
func (_u *QuizUpdateOne) SetOneAttempt(v bool) *QuizUpdateOne {
	_u.mutation.SetOneAttempt(v)
	return _u
}

// SetNillableOneAttempt sets the "one_attempt" field if the given value is not nil.
func (_u *QuizUpdateOne) SetNillableOneAttempt(v *bool) *QuizUpdateOne {
	if v != nil {
		_u.SetOneAttempt(*v)
	}
	return _u
}

// SetShowAnswers sets the "show_answers" field.
func (_u *QuizUpdateOne) SetShowAnswers(v bool) *QuizUpdateOne {
	_u.mutation.SetShowAnswers(v)
	return _u
}

// SetNillableShowAnswers sets the "show_answers" field if the given value is not nil.
func (_u *QuizUpdateOne) SetNillableShowAnswers(v *bool) *QuizUpdateOne {
	if v != nil {
		_u.SetShowAnswers(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *QuizUpdateOne) SetCreatedAt(v time.Time) *QuizUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *QuizUpdateOne) SetNillableCreatedAt(v *time.Time) *QuizUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *QuizUpdateOne) SetCreatorID(id int) *QuizUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *QuizUpdateOne) SetCreator(v *User) *QuizUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddQuestionIDs adds the "questions" edge to the Questions entity by IDs.
func (_u *QuizUpdateOne) AddQuestionIDs(ids ...int) *QuizUpdateOne {
	_u.mutation.AddQuestionIDs(ids...)
	return _u
}

// AddQuestions adds the "questions" edges to the Questions entity.
func (_u *QuizUpdateOne) AddQuestions(v ...*Questions) *QuizUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestionIDs(ids...)
}

// AddAttemptIDs adds the "attempts" edge to the Attempt entity by IDs.
func (_u *QuizUpdateOne) AddAttemptIDs(ids ...int) *QuizUpdateOne {
	_u.mutation.AddAttemptIDs(ids...)
	return _u
}

// AddAttempts adds the "attempts" edges to the Attempt entity.
func (_u *QuizUpdateOne) AddAttempts(v ...*Attempt) *QuizUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptIDs(ids...)
}

// Mutation returns the QuizMutation object of the builder.
func (_u *QuizUpdateOne) Mutation() *QuizMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *QuizUpdateOne) ClearCreator() *QuizUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearQuestions clears all "questions" edges to the Questions entity.
func (_u *QuizUpdateOne) ClearQuestions() *QuizUpdateOne {
	_u.mutation.ClearQuestions()
	return _u
}

// RemoveQuestionIDs removes the "questions" edge to Questions entities by IDs.
func (_u *QuizUpdateOne) RemoveQuestionIDs(ids ...int) *QuizUpdateOne {
	_u.mutation.RemoveQuestionIDs(ids...)
	return _u
}

// RemoveQuestions removes "questions" edges to Questions entities.
func (_u *QuizUpdateOne) RemoveQuestions(v ...*Questions) *QuizUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestionIDs(ids...)
}

// ClearAttempts clears all "attempts" edges to the Attempt entity.
func (_u *QuizUpdateOne) ClearAttempts() *QuizUpdateOne {
	_u.mutation.ClearAttempts()
	return _u
}

// RemoveAttemptIDs removes the "attempts" edge to Attempt entities by IDs.
func (_u *QuizUpdateOne) RemoveAttemptIDs(ids ...int) *QuizUpdateOne {
	_u.mutation.RemoveAttemptIDs(ids...)
	return _u
}

// RemoveAttempts removes "attempts" edges to Attempt entities.
func (_u *QuizUpdateOne) RemoveAttempts(v ...*Attempt) *QuizUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptIDs(ids...)
}

// Where appends a list predicates to the QuizUpdate builder.
func (_u *QuizUpdateOne) Where(ps ...predicate.Quiz) *QuizUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuizUpdateOne) Select(field string, fields ...string) *QuizUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Quiz entity.
func (_u *QuizUpdateOne) Save(ctx context.Context) (*Quiz, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizUpdateOne) SaveX(ctx context.Context) *Quiz {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuizUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizUpdateOne) check() error {
	if v, ok := _u.mutation.PassThreshold(); ok {
		if err := quiz.PassThresholdValidator(v); err != nil {
			return &ValidationError{Name: "pass_threshold", err: fmt.Errorf(`ent: validator failed for field "Quiz.pass_threshold": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Quiz.creator"`)
	}
	return nil
}

func (_u *QuizUpdateOne) sqlSave(ctx context.Context) (_node *Quiz, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quiz.Table, quiz.Columns, sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Quiz.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quiz.FieldID)
		for _, f := range fields {
			if !quiz.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quiz.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(quiz.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(quiz.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PassThreshold(); ok {
		_spec.SetField(quiz.FieldPassThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassThreshold(); ok {
		_spec.AddField(quiz.FieldPassThreshold, field.TypeInt, value)
	}
	if _u.mutation.PassThresholdCleared() {
		_spec.ClearField(quiz.FieldPassThreshold, field.TypeInt)
	}
	if value, ok := _u.mutation.OneAttempt(); ok {
		_spec.SetField(quiz.FieldOneAttempt, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShowAnswers(); ok {
		_spec.SetField(quiz.FieldShowAnswers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(quiz.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.CreatorTable,
			Columns: []string{quiz.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.CreatorTable,
			Columns: []string{quiz.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestionsIDs(); len(nodes) > 0 && !_u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptsIDs(); len(nodes) > 0 && !_u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Quiz{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quiz.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
