// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"quizsystem/internal/store/ent/attempt"
	"quizsystem/internal/store/ent/questions"
	"quizsystem/internal/store/ent/quiz"
	"quizsystem/internal/store/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizCreate is the builder for creating a Quiz entity.
type QuizCreate struct {
	config
	mutation *QuizMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *QuizCreate) SetTitle(v string) *QuizCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetIsPublished sets the "is_published" field.
func (_c *QuizCreate) SetIsPublished(v bool) *QuizCreate {
	_c.mutation.SetIsPublished(v)
	return _c
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_c *QuizCreate) SetNillableIsPublished(v *bool) *QuizCreate {
	if v != nil {
		_c.SetIsPublished(*v)
	}
	return _c
}

// SetPassThreshold sets the "pass_threshold" field.
func (_c *QuizCreate) SetPassThreshold(v int) *QuizCreate {
	_c.mutation.SetPassThreshold(v)
	return _c
}

// SetNillablePassThreshold sets the "pass_threshold" field if the given value is not nil.
func (_c *QuizCreate) SetNillablePassThreshold(v *int) *QuizCreate {
	if v != nil {
		_c.SetPassThreshold(*v)
	}
	return _c
}

// SetOneAttempt sets the "one_attempt" field.
func (_c *QuizCreate) SetOneAttempt(v bool) *QuizCreate {
	_c.mutation.SetOneAttempt(v)
	return _c
}

// SetNillableOneAttempt sets the "one_attempt" field if the given value is not nil.
func (_c *QuizCreate) SetNillableOneAttempt(v *bool) *QuizCreate {
	if v != nil {
		_c.SetOneAttempt(*v)
	}
	return _c
}

// SetShowAnswers sets the "show_answers" field.
func (_c *QuizCreate) SetShowAnswers(v bool) *QuizCreate {
	_c.mutation.SetShowAnswers(v)
	return _c
}

// SetNillableShowAnswers sets the "show_answers" field if the given value is not nil.
func (_c *QuizCreate) SetNillableShowAnswers(v *bool) *QuizCreate {
	if v != nil {
		_c.SetShowAnswers(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuizCreate) SetCreatedAt(v time.Time) *QuizCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuizCreate) SetNillableCreatedAt(v *time.Time) *QuizCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *QuizCreate) SetCreatorID(id int) *QuizCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *QuizCreate) SetCreator(v *User) *QuizCreate {
	return _c.SetCreatorID(v.ID)
}

// AddQuestionIDs adds the "questions" edge to the Questions entity by IDs.
func (_c *QuizCreate) AddQuestionIDs(ids ...int) *QuizCreate {
	_c.mutation.AddQuestionIDs(ids...)
	return _c
}

// AddQuestions adds the "questions" edges to the Questions entity.
func (_c *QuizCreate) AddQuestions(v ...*Questions) *QuizCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddQuestionIDs(ids...)
}

// AddAttemptIDs adds the "attempts" edge to the Attempt entity by IDs.
func (_c *QuizCreate) AddAttemptIDs(ids ...int) *QuizCreate {
	_c.mutation.AddAttemptIDs(ids...)
	return _c
}

// AddAttempts adds the "attempts" edges to the Attempt entity.
func (_c *QuizCreate) AddAttempts(v ...*Attempt) *QuizCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttemptIDs(ids...)
}

// Mutation returns the QuizMutation object of the builder.
func (_c *QuizCreate) Mutation() *QuizMutation {
	return _c.mutation
}

// Save creates the Quiz in the database.
func (_c *QuizCreate) Save(ctx context.Context) (*Quiz, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuizCreate) SaveX(ctx context.Context) *Quiz {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuizCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuizCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuizCreate) defaults() {
	if _, ok := _c.mutation.IsPublished(); !ok {
		v := quiz.DefaultIsPublished
		_c.mutation.SetIsPublished(v)
	}
	if _, ok := _c.mutation.OneAttempt(); !ok {
		v := quiz.DefaultOneAttempt
		_c.mutation.SetOneAttempt(v)
	}
	if _, ok := _c.mutation.ShowAnswers(); !ok {
		v := quiz.DefaultShowAnswers
		_c.mutation.SetShowAnswers(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quiz.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuizCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Quiz.title"`)}
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		return &ValidationError{Name: "is_published", err: errors.New(`ent: missing required field "Quiz.is_published"`)}
	}
	if v, ok := _c.mutation.PassThreshold(); ok {
		if err := quiz.PassThresholdValidator(v); err != nil {
			return &ValidationError{Name: "pass_threshold", err: fmt.Errorf(`ent: validator failed for field "Quiz.pass_threshold": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OneAttempt(); !ok {
		return &ValidationError{Name: "one_attempt", err: errors.New(`ent: missing required field "Quiz.one_attempt"`)}
	}
	if _, ok := _c.mutation.ShowAnswers(); !ok {
		return &ValidationError{Name: "show_answers", err: errors.New(`ent: missing required field "Quiz.show_answers"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Quiz.created_at"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Quiz.creator"`)}
	}
	return nil
}

func (_c *QuizCreate) sqlSave(ctx context.Context) (*Quiz, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuizCreate) createSpec() (*Quiz, *sqlgraph.CreateSpec) {
	var (
		_node = &Quiz{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quiz.Table, sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(quiz.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.IsPublished(); ok {
		_spec.SetField(quiz.FieldIsPublished, field.TypeBool, value)
		_node.IsPublished = value
	}
	if value, ok := _c.mutation.PassThreshold(); ok {
		_spec.SetField(quiz.FieldPassThreshold, field.TypeInt, value)
		_node.PassThreshold = &value
	}
	if value, ok := _c.mutation.OneAttempt(); ok {
		_spec.SetField(quiz.FieldOneAttempt, field.TypeBool, value)
		_node.OneAttempt = value
	}
	if value, ok := _c.mutation.ShowAnswers(); ok {
		_spec.SetField(quiz.FieldShowAnswers, field.TypeBool, value)
		_node.ShowAnswers = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quiz.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.CreatorTable,
			Columns: []string{quiz.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_quizzes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.AttemptsTable,
			Columns: []string{quiz.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attempt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuizCreateBulk is the builder for creating many Quiz entities in bulk.
type QuizCreateBulk struct {
	config
	err      error
	builders []*QuizCreate
}

// Save creates the Quiz entities in the database.
func (_c *QuizCreateBulk) Save(ctx context.Context) ([]*Quiz, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Quiz, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuizMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuizCreateBulk) SaveX(ctx context.Context) []*Quiz {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuizCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuizCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
