// Code generated by ent, DO NOT EDIT.

package ent

import (
	"quizsystem/internal/store/ent/answers"
	"quizsystem/internal/store/ent/attempt"
	"quizsystem/internal/store/ent/quiz"
	"quizsystem/internal/store/ent/schema"
	"quizsystem/internal/store/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	answersFields := schema.Answers{}.Fields()
	_ = answersFields
	// answersDescIsCorrect is the schema descriptor for is_correct field.
	answersDescIsCorrect := answersFields[1].Descriptor()
	// answers.DefaultIsCorrect holds the default value on creation for the is_correct field.
	answers.DefaultIsCorrect = answersDescIsCorrect.Default.(bool)
	attemptFields := schema.Attempt{}.Fields()
	_ = attemptFields
	// attemptDescScore is the schema descriptor for score field.
	attemptDescScore := attemptFields[0].Descriptor()
	// attempt.ScoreValidator is a validator for the "score" field. It is called by the builders before save.
	attempt.ScoreValidator = attemptDescScore.Validators[0].(func(int) error)
	// attemptDescTotal is the schema descriptor for total field.
	attemptDescTotal := attemptFields[1].Descriptor()
	// attempt.TotalValidator is a validator for the "total" field. It is called by the builders before save.
	attempt.TotalValidator = attemptDescTotal.Validators[0].(func(int) error)
	// attemptDescCreatedAt is the schema descriptor for created_at field.
	attemptDescCreatedAt := attemptFields[2].Descriptor()
	// attempt.DefaultCreatedAt holds the default value on creation for the created_at field.
	attempt.DefaultCreatedAt = attemptDescCreatedAt.Default.(func() time.Time)
	quizFields := schema.Quiz{}.Fields()
	_ = quizFields
	// quizDescIsPublished is the schema descriptor for is_published field.
	quizDescIsPublished := quizFields[1].Descriptor()
	// quiz.DefaultIsPublished holds the default value on creation for the is_published field.
	quiz.DefaultIsPublished = quizDescIsPublished.Default.(bool)
	// quizDescPassThreshold is the schema descriptor for pass_threshold field.
	quizDescPassThreshold := quizFields[2].Descriptor()
	// quiz.PassThresholdValidator is a validator for the "pass_threshold" field. It is called by the builders before save.
	quiz.PassThresholdValidator = quizDescPassThreshold.Validators[0].(func(int) error)
	// quizDescOneAttempt is the schema descriptor for one_attempt field.
	quizDescOneAttempt := quizFields[3].Descriptor()
	// quiz.DefaultOneAttempt holds the default value on creation for the one_attempt field.
	quiz.DefaultOneAttempt = quizDescOneAttempt.Default.(bool)
	// quizDescShowAnswers is the schema descriptor for show_answers field.
	quizDescShowAnswers := quizFields[4].Descriptor()
	// quiz.DefaultShowAnswers holds the default value on creation for the show_answers field.
	quiz.DefaultShowAnswers = quizDescShowAnswers.Default.(bool)
	// quizDescCreatedAt is the schema descriptor for created_at field.
	quizDescCreatedAt := quizFields[5].Descriptor()
	// quiz.DefaultCreatedAt holds the default value on creation for the created_at field.
	quiz.DefaultCreatedAt = quizDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
